# Generated by Django 6.0.1 on 2026-01-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_rename_code_station_traincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
    ]
