# Generated by Django 6.0.1 on 2026-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
