# Generated by Django 6.0.1 on 2026-01-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('trains', '0002_rename_code_station_traincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traincache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_station_code', models.CharField(max_length=11)),
                ('journey_time', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cache', to='trains.train')),
            ],
        ),
    ]
