# Generated by Django 6.0.1 on 2026-01-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_traincache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traincache',
            old_name='current_station_code',
            new_name='current_station_name',
        ),
    ]
