# Generated by Django 6.0.1 on 2026-01-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_rename_current_station_code_traincache_current_station_name'),
        ('trains', '0003_remove_station_latitude_remove_station_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traincache',
            name='current_station_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('train', 'stop_number')},
        ),
    ]
