# Generated by Django 6.0.1 on 2026-01-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_traincache_current_station_name_and_more'),
        ('trains', '0003_remove_station_latitude_remove_station_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', models.JSONField()),
                ('distance_km', models.IntegerField()),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='trains.train')),
            ],
        ),
    ]
