# Generated by Django 6.0.1 on 2026-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_trainpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainpath',
            name='distance_km',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
