# Generated by Django 6.0.1 on 2026-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_trainpath_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincache',
            name='low_network_alerts',
            field=models.JSONField(default=list),
        ),
    ]
